### ISSUE TITLE
Please update Akka from 2.3.x to 2.4.x

### ISSUE THREAD

**Issue by ngocdaothanh** [lloydmeta/schwatcher#57]
Akka 2.4.x has been released:
* 2.4.1: https://groups.google.com/forum/#!topic/akka-user/-_uPosuZ3D8
* 2.4.0: https://groups.google.com/forum/#!topic/akka-user/iLDhogOMOoQ

BIG changes:
* Java 8 is required.
* Dropped support for Scala 2.10.

Migration Guide 2.3.x to 2.4.x:
http://doc.akka.io/docs/akka/2.4.1/project/migration-guide-2.3.x-2.4.x.html

**Comment by lloydmeta** [comment]
Interesting. The dropping of Java8 and Scala 2.10.x support hurts, but I guess the rest of the Scala community will be following suite. Done as part of #58
