### ISSUE TITLE
~10 second delay on ENTRY_MODIFY triggering

### ISSUE THREAD

**Issue by brainstorm** [lloydmeta/schwatcher#59]
Hi @lloydmeta, thanks for publishing this project, makes my little experiment with scala and filesystem watchers all that more pleasant :)

I have been playing with both RxMonitor and Akka actor models as detailed in the documentation and I've noticed that there's a significant delay when I create (`touch`) a file in a subdirectory that goes between 3 to 10 seconds from creating the file to actually getting a message with `println` back from a callback.

Reading through `WatchServiceTask.scala` I saw this:

https://github.com/lloydmeta/schwatcher/blob/master/src/main/scala/com/beachape/filemanagement/WatchServiceTask.scala#L56

Is there any way to overcome this sleep/delay? For my project I would need a system that reacts to changes much faster (ideally under a second).

Thanks in advance!

/ping @chris-zen

**Comment by lloydmeta** [comment]
Hi there, 

Good point; with 0.3.0, I [removed that particular sleep](https://github.com/lloydmeta/schwatcher/pull/56/files#diff-87763e887ef29de67ed5c9ade23f761fL56), replacing it with [a shorter sleep](https://github.com/lloydmeta/schwatcher/pull/56/files#diff-d4627ae3f0e9659e7f350279266f9346R106) for just deduping modify events.  This shortened the delay on my end, but it doesn't eliminate it completely.

If you are willing to live with possibly multiple notifications firing for the same modify event, you could set dedupe time to zero when [instantiating the monitoring actor](https://github.com/lloydmeta/schwatcher/blob/master/src/main/scala/com/beachape/filemanagement/MonitorActor.scala#L26). 

Would definitely be open to ideas to further cut down the delay without compromise though !!

**Comment by brainstorm** [comment]
Not sure how the best way would be to dedup/filter those events. Since our objective is to connect all this to kafka, maybe it's reasonable to handle those repeated events later downstream in kafka? What do you think @chris-zen?

**Comment by chris-zen** [comment]
I discovered that the delay was because the implementation in Mac OS of the WatchService is doing pulling and not using neither kqueues nor fsnotify. This explains why changing the dedupeTime for this lib we didn't notice any change.

**Comment by lloydmeta** [comment]
@chris-zen nice find; I didn't know you were on OSX. In that case, you might want to try setting a `Modifier` (e.g. `SensitivityWatchEventModifier.HIGH`) when registering a callback:

https://github.com/lloydmeta/schwatcher/blob/master/src/main/scala/com/beachape/filemanagement/Messages.scala#L51
