### ISSUE TITLE
Sending events directly to an ActorRef instead of the callback

### ISSUE THREAD

**Issue by chris-zen** [lloydmeta/schwatcher#60]
Hi,

I would like to process the events using Akka actors too, but I didn't find any option to specify a receiver actor, just the callback. It's true that I can forward the event directly from inside the callback to my actors, but I was just wondering if you were considering making this a first class option.

Thanks

/ping @brainstorm

**Comment by lloydmeta** [comment]
This is definitely a good idea, to offer an API that forwards events to Actors.

Thinking that one way to do it would be to have messages that take an `ActorRef` (e.g. `RegisterSubscriber`) and internally it can still be implemented with callbacks.

**Comment by lloydmeta** [comment]
I just pushed 0.3.1-SNAPSHOT to Sonatype which adds an API for sending `EventAtPath` events directly to an `ActorRef`.  API looks something like this:

```scala
monitorActor ! RegisterSubscriber(event = ENTRY_MODIFY, path = filePath, subscriber = actorRef)
```
