### ISSUE TITLE
> 5 seconds delay between FS change and the callback execution on MacOS(Duplicate)

### ISSUE THREAD

**Issue by eugengarkusha** [lloydmeta/schwatcher#62]
Known issue of JDK but there is a one-liner workaround that you might want to implement:

http://stackoverflow.com/questions/9588737/is-java-7-watchservice-slow-for-anyone-else

This would be very helpful for Mac users(including me ))).

Thanks!

**Comment by eugengarkusha** [comment]
sorry, i see that it is  a duplicate of : 
https://github.com/lloydmeta/schwatcher/issues/59

**Comment by lloydmeta** [comment]
Have you tried setting the modifier option when registering your callback? 

https://github.com/lloydmeta/schwatcher/blob/master/src/main/scala/com/beachape/filemanagement/Messages.scala#L69

**Comment by eugengarkusha** [comment]
Yes sure, thanks!
Beg your pardon for this false alarm.

**Comment by lloydmeta** [comment]
No worries :) closing for now.
