### ISSUE TITLE
Cannot monitor creation of a file when parent directory does not pre-exist

### ISSUE THREAD

**Issue by Sciss** [lloydmeta/schwatcher#74]
Thank you for this library.
Say, I want to wait for a creation of file `/a/b/c` and `/a` exists, but `/a/b` does not yet exist. I can't get an event to fire here, even if checking `recursive = true` (I guess it is meant for this case?)

https://github.com/Sciss/schwatcher/blob/11a4e19f933a5ca27f8c611f9dddf5ad4c6d0f15/src/test/scala/de/sciss/foo/SomeTests.scala

**Comment by lloydmeta** [comment]
Wow, it's been a while since I've looked at this library :)

Can you give `persistent = true` a try? Recursive is for controlling whether or not to watch all sub directories.

**Comment by Sciss** [comment]
Thank you; `persistent` did the job.
