### ISSUE TITLE
Contribution policy

### ISSUE THREAD

**Issue by Sciss** [lloydmeta/schwatcher#75]
Hi there. I will probably be using this library, and I wonder what the policy for contributing to the library are. Examples:

- I can see that scalafmt is used for code formatting, but there are multiple highlight issues in IntelliJ such as unnecessary braces for case blocks, some typos in comments etc. Would you be interested in having those cleaned up?
- Factoring into two modules to get rid of RxScala dependency in a new "core" project?
- Adding Scala 2.13 support
- Updating dependencies (latest sbt, latest Akka etc.)

**Comment by lloydmeta** [comment]
👍 to all of the above :)
